CulturalHeritageWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace CulturalHeritageWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Education()
        {
            return View();
        }
    }
}

CulturalHeritageWebApp/Controllers/LocationsController.cs
using AutoMapper;
using CulturalHeritageBL.BLModels;
using CulturalHeritageBL.DALModels;
using CulturalHeritageBL.Repositories;
using CulturalHeritageWebApp.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Net;

namespace CulturalHeritageWebApp.Controllers
{
    public class LocationsController : Controller
    {
        private readonly IHeritageRepository _heritageRepo;
        private readonly IAgeCategoryRepository _ageCategoryRepo;
        private readonly IHeritageCategoryRepository _heritageCategoryRepo;
        private readonly IMapper _mapper;
        private readonly CulturalHeritageContext _dbContext;

        private const string location = "Location";

        public LocationsController(IHeritageRepository heritageRepo, IAgeCategoryRepository ageCategoryRepo, IHeritageCategoryRepository heritageCategoryRepo, IMapper mapper, CulturalHeritageContext dbContext)
        {
            _heritageRepo = heritageRepo;
            _ageCategoryRepo = ageCategoryRepo;
            _heritageCategoryRepo = heritageCategoryRepo;
            _mapper = mapper;
            _dbContext = dbContext;
    }
         
        // GET: LocationsController
        public ActionResult Index()
        {
            var blLocations = _heritageRepo.GetAllHeritage().
                        Where(a => a.HeritageCategory.Name == location);
            var vmLocations = _mapper.Map<IEnumerable<VMHeritage>>(blLocations);

            return View(vmLocations);
        }

        // GET: LocationsController/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound("Location not found!");
            }

            var blLocation = _heritageRepo.GetHeritage(id);
            var vmLocation = _mapper.Map<VMHeritage>(blLocation);

            if (vmLocation == null)
            {
                return NotFound("Location not found!");
            }

            return View(vmLocation);
        }

        // GET: LocationsController/Create
        public ActionResult Create()
        {
            var ageCategories = _ageCategoryRepo.GetAllAgeCategories().ToList();

            var ageCategoryList = new SelectList(ageCategories, "IDAgeCategory", "Name");
                        

            var viewModel = new VMHeritage()
            {
                HeritageCategoryID = _heritageCategoryRepo.GetHeritageCategoryID(location),
                AgeCategoryList = ageCategoryList
            };

            return View(viewModel);
        }

        // POST: LocationsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Heritage heritage)
        {
            if (!ModelState.IsValid)
            {
                var ageCategories = _ageCategoryRepo.GetAllAgeCategories().ToList();

                var ageCategoryList = new SelectList(ageCategories, "IDAgeCategory", "Name");

                var viewModel = new VMHeritage()
                {
                    HeritageCategoryID = _heritageCategoryRepo.GetHeritageCategoryID(location),
                    AgeCategoryList = ageCategoryList,
                };

                return View(viewModel);
            }

            _heritageRepo.AddHeritage(heritage);
            return RedirectToAction(nameof(Index));          
        }

        // GET: LocationsController/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var heritage = _heritageRepo.GetHeritage(id);
            if (heritage == null)
            {
                return BadRequest();
            }

            var ageCategories = _ageCategoryRepo.GetAllAgeCategories().ToList();
            var ageCategoryList = new SelectList(ageCategories, "IDAgeCategory", "Name");

            var viewModel = new VMHeritage()
            {
                IDHeritage = heritage.IDHeritage,
                Title = heritage.Title,
                Description = heritage.Description,
                HeritageCategoryID = heritage.HeritageCategoryId,
                AgeCategoryID = heritage.AgeCategoryId,
                AgeCategoryList = ageCategoryList
            };

            return View(viewModel);
        }



        // POST: LocationsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Heritage heritage)
        {
            if (ModelState.IsValid)
            {
                var location = _dbContext.Heritages.Find(heritage.IDHeritage);

                if (location == null)
                {
                    return BadRequest(ModelState);
                }

                location.Title = heritage.Title;
                location.Description = heritage.Description;
                location.HeritageCategoryId = heritage.HeritageCategoryId;
                location.AgeCategoryId = heritage.AgeCategoryId;

                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(heritage);
        }

        // GET: LocationsController/Delete/5
        public ActionResult Delete(int id)
        {
            var blHeritage = _heritageRepo.GetHeritage(id);
            var vmHeritage = _mapper.Map<VMHeritage>(blHeritage);
            return View(vmHeritage);
        }

        // POST: LocationsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, VMHeritage heritage)
        {
            var location = _heritageRepo.GetHeritage(id);
            if (heritage == null)
            {
                return NotFound();
            }

            var photosToDelete = _dbContext.Photographies.Where(p => p.HeritageId == id);

            _dbContext.Photographies.RemoveRange(photosToDelete);
            _dbContext.SaveChanges();

            var videoToDelete = _dbContext.Videos.Where(p => p.HeritageId == id);

            _dbContext.Videos.RemoveRange(videoToDelete);
            _dbContext.SaveChanges();

            var heritageToDelete = _dbContext.Heritages.Find(id);
            if (heritageToDelete != null)
            {
                _heritageRepo.DeleteHeritage(heritageToDelete);                
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CulturalHeritageWebApp/Views/Home/About.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/homepage.css">
</head>
<body>
    <section class="sub-header">
        <nav>
            <img src="~/Photos/vase.png">
            <div class="nav-links" id="navLinks">
                <img src="~/Photos/closing.png" class="fa" style="width:15px; height: 15px" onclick="hideMenu()" />
                <ul>
                    <li><a asp-controller="Home" asp-action="Index">HOME <span>&vert;</span></a></li>
                    <li><a asp-controller="Locations" asp-action="Index">Cultural Locations <span>&vert;</span></a></li>
                    <li><a asp-controller="Intangible" asp-action="Index">Intangible Heritage <span>&vert;</span></a></li>
                    <li><a asp-controller="Tangible" asp-action="Index">Tangible Heritage <span>&vert;</span></a></li>
                    <li><a asp-controller="Home" asp-action="Education">Education  <span>&vert;</span></a></li>
                    <li><a asp-controller="Home" asp-action="About">About Us</a></li>
                </ul>
            </div>
            <img src="~/Photos/menu.png" style="width:25px; height: 25px" class="fa" onclick="showMenu()" />
        </nav>
        
        <h1>About Us</h1>

    </section>


    @*Our Mission*@

    <section class="about-us">

        <div class="row">
            <div class="about-col">
                <h1>Our Mission</h1>
                <p>
                    Preserving cultural heritage plays a pivotal role in safeguarding our identity, history, and values that shape our society. Our mission is dedicated to ensuring that cultural heritage remains accessible, protected, and conserved for present and future generations. Through our platform, we aim to raise awareness of the richness of cultural heritage, promote its preservation, and facilitate access to information, resources, and tools necessary for researching, interpreting, and advocating for cultural heritage worldwide.
                    Our mission encompasses the following objectives:
                    Facilitating access to cultural heritage through digital tools and resources.
                    Encouraging collaboration and knowledge-sharing among institutions, researchers, and enthusiasts devoted to preserving cultural heritage.
                    Educating and raising awareness about the significance of conserving cultural heritage to ensure its long-term preservation.
                    Promoting the diversity of cultural heritage and fostering understanding and respect for all facets of our past.
                </p>
                <h1>Our Vision</h1>
                <p>
                    Our vision is to create a platform that serves as a hub for exploring, sharing, collaborating, and advocating for cultural heritage, 
                    thereby recognizing its importance and value in our daily lives.
                </p>
                <a href="" class="hero-btn">EXPLORE NOW</a>
            </div>
            <div class="about-col">
                <img src="~/Photos/jordan.jpg">
            </div>
        </div>
    </section>

    <section class="sendComment">
        <div class="row">
            <div class="comment-box">
                <h3> Leave a comment</h3>
                <form class="comment-form">
                    <input type="text" placeholder="Enter Name">
                    <input type="email" placeholder="Enter Email">
                    <textarea rows="5" placeholder="Your comment"></textarea>
                    <button type="submit" class="hero-btn">
                        POST COMMENT
                    </button>
                </form>
            </div>
        </div>
    </section>


    @*Footer*@

    <section class="footer">
        <h4>About Us</h4>
        <p>
            Create. Protect. Share.
        </p>
        <div class="icons">
            <img src="~/Photos/face-logo.png" class="logo" />
            <img src="~/Photos/insta-logo.png" class="logo" />
            <img src="~/Photos/tik-tok-logo.png" class="logo" />
            <img src="~/Photos/x-logo.png" class="logo" />
        </div>
    </section>



    @*JavaSript for Toggle Menu*@
    <script src="~/js/site.js"></script>
</body>
</html>

CulturalHeritageWebApp/Views/Home/Education.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/education.css">
    
</head>
<body>
    <section class="header">
        <nav>
            <img src="~/Photos/vase.png">
            <div class="nav-links" id="navLinks">
                <img src="~/Photos/closing.png" class="fa" style="width:15px; height: 15px" onclick="hideMenu()" />
                <ul>
                    <li><a asp-controller="Home" asp-action="Index">HOME <span>&vert;</span></a></li>
                    <li><a asp-controller="Locations" asp-action="Index">Cultural Locations <span>&vert;</span></a></li>
                    <li><a asp-controller="Intangible" asp-action="Index">Intangible Heritage <span>&vert;</span></a></li>
                    <li><a asp-controller="Tangible" asp-action="Index">Tangible Heritage <span>&vert;</span></a></li>
                    <li><a asp-controller="Home" asp-action="Education">Education <span>&vert;</span></a></li>
                    <li><a asp-controller="Home" asp-action="About">About Us</a></li>
                </ul>
            </div>
            <img src="~/Photos/menu.png" style="width:25px; height: 25px" class="fa" onclick="showMenu()" />
        </nav>
        <div class="text-box">
            <h1>Discover more about Cultural Heritage</h1>
        </div>
    </section>

    <section class="courses">
        <h1> Watch Cultural Heritage Courses</h1>
        <div class="row">
            <div class="courses-col">
                <h4>Cultural Heritage Management</h4>
                <p>
                    Cultural heritage management involves the strategic planning, preservation, conservation, and promotion of various aspects of
                    cultural heritage within a given society or community. It encompasses a range of activities aimed at safeguarding and sustaining
                    cultural heritage for present and future generations.
                    The objectives of cultural heritage management typically revolve around: Preservation and Conservation, Promotion and Education,
                    Sustainable Development, Community Engagement and Participation.
                </p>
            </div>
            <div class="courses-col">
                <iframe width="500" height="315" src="https://www.youtube.com/embed/videoseries?si=RwrkHLmTG24R42jn&amp;list=PLbei-sAWFFVpJHx_Et2UJc3VVEFtWZrjZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </div>
        </div>
    </section>

    <section class="courses">
        <div class="row">
            <div class="courses-col">
                <h4>What is Cultural Heritage</h4>
                <p>
                    Cultural Heritage Course delves into the rich and diverse tapestry of human history, traditions, art, architecture, 
                    and practices that define various societies. It explores the significance and preservation of tangible and intangible 
                    cultural elements, imparting insights into the importance of safeguarding and promoting heritage for future generations. 
                    Through interdisciplinary studies, these courses cover topics such as heritage management, preservation techniques, community 
                    engagement, and the role of cultural heritage in sustainable development. Participants learn to appreciate, analyze, 
                    and contribute to the conservation and dissemination of cultural legacy, fostering a deeper understanding and respect for 
                    global heritage.
                </p>
            </div>
            <div class="courses-col">
                <iframe width="500" height="315" src="https://www.youtube.com/embed/CbnXgvCOuIg?si=aoIa4Wbelthq5yKh" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
          </div>
        </div>
    </section>

    <section class="courses">
        <div class="row">
            <div class="courses-col">
                <h4>Intangible Cultural Heritage</h4>
                <p>
                    An Intangible Cultural Heritage Course is an educational program focused on the invaluable aspects of culture 
                    that aren't tangible or physical but are deeply rooted in traditions, beliefs, expressions, and practices of communities worldwide. 
                    This course explores diverse elements like oral traditions, performing arts, rituals, social practices, craftsmanship, and 
                    traditional knowledge systems. It aims to understand, document, preserve, and transmit these intangible cultural expressions 
                    across generations. Through interdisciplinary approaches, learners study the significance of intangible heritage in shaping 
                    identities, fostering social cohesion, and contributing to sustainable development. Participants gain insights into safeguarding 
                    and promoting these rich cultural expressions, recognizing their profound impact on societies and global diversity.
                </p>
            </div>
            <div class="courses-col">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/d9ZHj4ihTog?si=WpKwfkNkCZcT2r_N" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </div>
        </div>
    </section>

    <section class="courses">
        <div class="row">
            <div class="courses-col">
                <h4>Indian Cultural Heritage - Indian Culture and Tradition</h4>
                <p>
                    An Indian Cultural Heritage Course is a comprehensive study of the multifaceted and rich heritage that encapsulates India's 
                    diverse cultural tapestry. This course delves into the depth and diversity of India's traditions, encompassing its ancient history, 
                    art, architecture, literature, music, dance, festivals, philosophies, religions, and languages. It offers a holistic understanding 
                    of India's cultural legacy, tracing its evolution across centuries and exploring the influences and contributions of various 
                    civilizations and dynasties.
                <br />
                    Students engage with India's cultural heritage through an interdisciplinary approach, exploring its regional variations, 
                    traditions, and customs. They gain insights into the spiritual and philosophical underpinnings that shape Indian culture, 
                    discovering its global impact and relevance in contemporary society. Through this course, learners appreciate India's rich 
                    heritage, understand its significance in shaping identities, fostering cultural pride, and contributing to the world's cultural 
                    mosaic.
                </p>
            </div>
            <div class="courses-col">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/lK3oqU2WNY0?si=1XEgWTk8aCkrjki6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
        </div>
    </section>



    <section class="playQuiz">
        <h1> Play Cultural Heritage Quiz  </h1>
        <div class="quiz-container">
            <h1>Cultural Heritage Quiz</h1>
            <div class="quiz">
                <h2 id="question"></h2>
                <div id="answer-buttons">
                    <button class="btn">Answer 1</button>
                    <button class="btn">Answer 2</button>
                    <button class="btn">Answer 3</button>
                    <button class="btn">Answer 4</button>
                </div>
                <button id="next-btn">Next</button>
            </div>

        </div>
    </section>




    @*Footer*@

    <section class="footer">
        <h4>About Us</h4>
        <p>
            Create. Protect. Share.
        </p>
        <div class="icons">
            <img src="~/Photos/face-logo.png" class="logo" />
            <img src="~/Photos/insta-logo.png" class="logo" />
            <img src="~/Photos/tik-tok-logo.png" class="logo" />
            <img src="~/Photos/x-logo.png" class="logo" />
        </div>
    </section>



    @*JavaSript for Toggle Menu*@
    <script src="~/js/site.js"></script>
    <script src="~/js/education.js"></script>

</body>
</html>

CulturalHeritageWebApp/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/homepage.css">
</head>
<body>
    <section class="header">
        <nav>
            <img src="~/Photos/vase.png">
            <div class="nav-links" id="navLinks">
                <img src="~/Photos/closing.png" class="fa" style="width:15px; height: 15px" onclick="hideMenu()"/>
                <ul>
                    <li><a asp-controller="Home" asp-action="Index">HOME <span>&vert;</span></a></li>
                    <li><a asp-controller="Locations" asp-action="Index">Cultural Locations <span>&vert;</span></a></li>
                    <li><a asp-controller="Intangible" asp-action="Index">Intangible Heritage <span>&vert;</span></a></li>
                    <li><a asp-controller="Tangible" asp-action="Index">Tangible Heritage <span>&vert;</span></a></li>
                    <li><a asp-controller="Home" asp-action="Education">Education <span>&vert;</span></a></li>
                    <li><a asp-controller="Home" asp-action="About">About Us</a></li>
                </ul>
            </div>
            <img src="~/Photos/menu.png" style="width:25px; height: 25px" class="fa" onclick="showMenu()" />
        </nav>
    <div class="text-box">
            <h1>CULTURAL HERITAGE PRESERVATION PLATFORM</h1>
            <p>Cultural heritage embodies the history, traditions, and values of a society. 
                It reflects our identity and provides a sense of belonging and continuity. <br />
                Preserving cultural heritage safeguards unique landmarks, artifacts, languages, and practices for future generations.</p>

            <a asp-controller="Home" asp-action="About" class="hero-btn">Read more about our work...</a>
    </div>
    </section>

    @*The Divisions of Cultural Heritage*@

    <section class="divisions">
        <h1>The Divisions of Cultural Heritage</h1>
        <p>Cultural heritage encompasses the unique expressions, traditions, artifacts, and values inherited from past generations, <br />representing a collective identity and enriching the diverse tapestry of human civilization.</p>
        
        <div class="row">
            <div class="divisions-col">
                <h3>Cultural Locations</h3>
                <p>Cultural locations refer to places of significance due to their cultural, historical, or artistic value. 
                    These locations often include museums, heritage sites, monuments, landmarks, religious buildings, archaeological sites, cultural 
                    centers, and other places that represent and preserve cultural identity, history, and heritage. They serve as repositories of 
                    cultural artifacts, traditions, and stories, offering insights into a society's past, values, and traditions.</p>
            </div>
            <div class="divisions-col">
                <h3>Intangible Heritage</h3>
                <p>Intangible heritage refers to cultural elements that are not physical objects but are instead based on cultural practices, traditions, 
                    expressions, knowledge, and skills passed down from generation to generation. These include traditions, rituals, performing arts, oral 
                    traditions, social practices, craftsmanship, knowledge about nature and the universe, languages, and other forms of intangible cultural 
                    expressions that communities, groups, or individuals recognize as part of their cultural heritage.</p>
            </div>
            <div class="divisions-col">
                <h3>Tangible Heritage</h3>
                <p>Tangible heritage comprises physical entities, encompassing structures, and objects that hold historical, cultural, 
                    artistic, or religious significance. It encompasses tangible elements such as sculptures, paintings, architectural masterpieces. 
                    This category embodies the physical manifestations of a culture's legacy, including artworks, 
                    monuments, artifacts, archaeological sites, and other material objects that reflect the cultural, social, 
                    or historical value of a community or civilization.</p>
            </div>
        </div>

    </section>


   @* Explore our Heritage Platform*@

    <section class="explore">
        <h1>Explore our Heritage Platform</h1>

        <div class="row">
            <div class="explore-col">
                <a asp-controller="Locations" asp-action="Index">
                <img src="~/Photos/pyrami.png">
                <div class="layer">
                    <h3>CULTURAL LOCATIONS</h3>
                </div>
                </a>
            </div>
            <div class="explore-col">
                <a asp-controller="Intangible" asp-action="Index">
                <img src="~/Photos/dancingGroup.png">
                <div class="layer">
                    <h3>INTANGIBLE HERITAGE</h3>
                </div>
                </a>
            </div>
            <div class="explore-col">
                <a asp-controller="Tangible" asp-action="Index">
                <img src="~/Photos/david-mic.png">
                <div class="layer">
                    <h3>TANGIBLE HERITAGE</h3>
                </div>
                </a>
            </div>
        </div>

    </section>

         @*Our Projects*@

    <section class="ourProjects">
        <h1>Our Projects</h1>

        <div class="row">
            <div class="ourprojects-col">
                <img src="~/Photos/iherit.png">
                <h3>iHERITAGE project: new experience of cultural heritage</h3>
                <p>New techniques to improve its level of interpretation, taking advantage of new technologies and commercialising the latest research results.</p>
            </div>
            <div class="ourprojects-col">
                <img src="~/Photos/techtransfer.png">
                <h3>TECHNOLOGY TRANSFER: sharing intellectual property with others</h3>
                <p>Movement of data, designs, inventions, materials, software, technical knowledge or trade secrets from one organisation to another or from one purpose to another.</p>
            </div>
            <div class="ourprojects-col">
                <img src="~/Photos/social.png">
                <h3>SOCIAL INCLUSION: ensure equal opportunities</h3>
                <p>Improving the terms on which individuals and groups take part in society—improving the ability, opportunity, and dignity of those disadvantaged on the basis of their identity.</p>
            </div>
        </div>
    </section>

    @*Comments*@

    <section class="comments">
        <h1>What our partners say</h1>

        <div class="row">
            <div class="comments-col">
                <img src="~/Photos/user1.png"> 
                <div>
                    <p>
                        Participating in the iHeritage project was an incredibly enriching experience! It provided a platform to delve into diverse cultural heritages, fostering a deeper understanding of our shared history and traditions. The project's collaborative nature encouraged learning, appreciation, and preservation of invaluable cultural legacies.
                    </p>
                    <h3>Chris Maloni</h3>
                    <img src="~/Photos/star.png" class="star">
                    <img src="~/Photos/star.png" class="star">
                    <img src="~/Photos/star.png" class="star">
                    <img src="~/Photos/star.png" class="star">
                    <img src="~/Photos/star.png" class="star">
                </div>
            </div>
            <div class="comments-col">
                <img src="~/Photos/user2.png">
                <div>
                    <p>
                        Being a part of the iHeritage project was an enlightening journey into the depths of cultural diversity. It offered a unique opportunity to celebrate and safeguard our heritage, fostering a sense of unity and respect for the rich tapestry of cultures that shape our world. Great experience working with motivated people.
                    </p>
                    <h3>David Johnson</h3>
                    <img src="~/Photos/star.png" class="star">
                    <img src="~/Photos/star.png" class="star">
                    <img src="~/Photos/star.png" class="star">
                    <img src="~/Photos/star.png" class="star">
                    <img src="~/Photos/rating.png" class="star">
                </div>
            </div>
        </div>

    </section>

     @*Enroll*@

    <section class="enroll">
        <h1>Enroll in our projects <br /> Take part in preserving cultural heritage</h1>
        <a asp-controller="Home" asp-action="About" class="hero-btn">CONTACT US</a>
    </section>


    @*Footer*@

    <section class="footer">
        <h4>About Us</h4>
        <p>
            Create. Protect. Share.
        </p>
        <div class="icons">
            <img src="~/Photos/face-logo.png" class="logo"/>
            <img src="~/Photos/insta-logo.png" class="logo" />
            <img src="~/Photos/tik-tok-logo.png" class="logo" />
            <img src="~/Photos/x-logo.png" class="logo" />
        </div>
    </section>

    @*JavaSript for Toggle Menu*@
    <script src="~/js/site.js"></script>
</body>
</html>