CulturalHeritageWebApp/Controllers/LocationsController.cs
using AutoMapper;
using CulturalHeritageBL.BLModels;
using CulturalHeritageBL.DALModels;
using CulturalHeritageBL.Repositories;
using CulturalHeritageWebApp.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Net;

namespace CulturalHeritageWebApp.Controllers
{
    public class LocationsController : Controller
    {
        private readonly IHeritageRepository _heritageRepo;
        private readonly IAgeCategoryRepository _ageCategoryRepo;
        private readonly IHeritageCategoryRepository _heritageCategoryRepo;
        private readonly IMapper _mapper;
        private readonly CulturalHeritageContext _dbContext;

        private const string location = "Location";

        public LocationsController(IHeritageRepository heritageRepo, IAgeCategoryRepository ageCategoryRepo, IHeritageCategoryRepository heritageCategoryRepo, IMapper mapper, CulturalHeritageContext dbContext)
        {
            _heritageRepo = heritageRepo;
            _ageCategoryRepo = ageCategoryRepo;
            _heritageCategoryRepo = heritageCategoryRepo;
            _mapper = mapper;
            _dbContext = dbContext;
    }
         
        // GET: LocationsController
        public ActionResult Index()
        {
            var blLocations = _heritageRepo.GetAllHeritage().
                        Where(a => a.HeritageCategory.Name == location);
            var vmLocations = _mapper.Map<IEnumerable<VMHeritage>>(blLocations);

            return View(vmLocations);
        }

        // GET: LocationsController/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound("Location not found!");
            }

            var blLocation = _heritageRepo.GetHeritage(id);
            var vmLocation = _mapper.Map<VMHeritage>(blLocation);

            if (vmLocation == null)
            {
                return NotFound("Location not found!");
            }

            return View(vmLocation);
        }

        // GET: LocationsController/Create
        public ActionResult Create()
        {
            var ageCategories = _ageCategoryRepo.GetAllAgeCategories().ToList();

            var ageCategoryList = new SelectList(ageCategories, "IDAgeCategory", "Name");
                        

            var viewModel = new VMHeritage()
            {
                HeritageCategoryID = _heritageCategoryRepo.GetHeritageCategoryID(location),
                AgeCategoryList = ageCategoryList
            };

            return View(viewModel);
        }

        // POST: LocationsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Heritage heritage)
        {
            if (!ModelState.IsValid)
            {
                var ageCategories = _ageCategoryRepo.GetAllAgeCategories().ToList();

                var ageCategoryList = new SelectList(ageCategories, "IDAgeCategory", "Name");

                var viewModel = new VMHeritage()
                {
                    HeritageCategoryID = _heritageCategoryRepo.GetHeritageCategoryID(location),
                    AgeCategoryList = ageCategoryList,
                };

                return View(viewModel);
            }

            _heritageRepo.AddHeritage(heritage);
            return RedirectToAction(nameof(Index));          
        }

        // GET: LocationsController/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var heritage = _heritageRepo.GetHeritage(id);
            if (heritage == null)
            {
                return BadRequest();
            }

            var ageCategories = _ageCategoryRepo.GetAllAgeCategories().ToList();
            var ageCategoryList = new SelectList(ageCategories, "IDAgeCategory", "Name");

            var viewModel = new VMHeritage()
            {
                IDHeritage = heritage.IDHeritage,
                Title = heritage.Title,
                Description = heritage.Description,
                HeritageCategoryID = heritage.HeritageCategoryId,
                AgeCategoryID = heritage.AgeCategoryId,
                AgeCategoryList = ageCategoryList
            };

            return View(viewModel);
        }



        // POST: LocationsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Heritage heritage)
        {
            if (ModelState.IsValid)
            {
                var location = _dbContext.Heritages.Find(heritage.IDHeritage);

                if (location == null)
                {
                    return BadRequest(ModelState);
                }

                location.Title = heritage.Title;
                location.Description = heritage.Description;
                location.HeritageCategoryId = heritage.HeritageCategoryId;
                location.AgeCategoryId = heritage.AgeCategoryId;

                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(heritage);
        }

        // GET: LocationsController/Delete/5
        public ActionResult Delete(int id)
        {
            var blHeritage = _heritageRepo.GetHeritage(id);
            var vmHeritage = _mapper.Map<VMHeritage>(blHeritage);
            return View(vmHeritage);
        }

        // POST: LocationsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, VMHeritage heritage)
        {
            var location = _heritageRepo.GetHeritage(id);
            if (heritage == null)
            {
                return NotFound();
            }

            var photosToDelete = _dbContext.Photographies.Where(p => p.HeritageId == id);

            _dbContext.Photographies.RemoveRange(photosToDelete);
            _dbContext.SaveChanges();

            var videoToDelete = _dbContext.Videos.Where(p => p.HeritageId == id);

            _dbContext.Videos.RemoveRange(videoToDelete);
            _dbContext.SaveChanges();

            var heritageToDelete = _dbContext.Heritages.Find(id);
            if (heritageToDelete != null)
            {
                _heritageRepo.DeleteHeritage(heritageToDelete);                
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CulturalHeritageWebApp/Controllers/PhotographyController.cs
using AutoMapper;
using CulturalHeritageBL.DALModels;
using CulturalHeritageBL.Repositories;
using CulturalHeritageWebApp.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;

namespace CulturalHeritageWebApp.Controllers
{
    public class PhotographyController : Controller
    {
        private readonly IPhotographyRepository _photoRepo;
        private readonly IMapper _mapper;
        private readonly CulturalHeritageContext _dbContext;


        public PhotographyController(IPhotographyRepository photoRepo, IMapper mapper, CulturalHeritageContext dbContext)
        {
            _photoRepo = photoRepo;
            _mapper = mapper;
            _dbContext = dbContext;
        }



        // GET: PhotographyController
        public ActionResult Index()
        {
            return View();
        }

        // GET: PhotographyController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PhotographyController/Create
        public ActionResult Create(int heritageID)
        {
            var viewModel = new VMPhotography
            {
                HeritageId = heritageID
            };

            return View(viewModel);
        }

        // POST: PhotographyController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Photography photo)
        {
            if (!ModelState.IsValid)
            {

                var viewModel = new VMPhotography
                {
                    HeritageId = photo.HeritageId
                };

                return View(viewModel);
            }

            _dbContext.Photographies.Add(photo);
            _dbContext.SaveChanges();
            return RedirectToAction("Index", "Locations");
        }

        // GET: PhotographyController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PhotographyController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PhotographyController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PhotographyController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CulturalHeritageWebApp/Controllers/VideoController.cs
using AutoMapper;
using CulturalHeritageBL.DALModels;
using CulturalHeritageBL.Repositories;
using CulturalHeritageWebApp.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CulturalHeritageWebApp.Controllers
{
    public class VideoController : Controller
    {
        private readonly IVideoRepository _videoRepo;
        private readonly IMapper _mapper;
        private readonly CulturalHeritageContext _dbContext;


        public VideoController(IVideoRepository videoRepo, IMapper mapper, CulturalHeritageContext dbContext)
        {
            _videoRepo = videoRepo;
            _mapper = mapper;
            _dbContext = dbContext;
        }


        // GET: VideoController
        public ActionResult Index()
        {
            return View();
        }

        // GET: VideoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: VideoController/Create
        public ActionResult Create(int heritageID)
        {
            var viewModel = new VMVideo
            {
                HeritageId = heritageID
            };

            return View(viewModel);
        }

        // POST: VideoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Video video)
        {
            if (!ModelState.IsValid)
            {

                var viewModel = new VMVideo
                {
                    HeritageId = video.HeritageId
                };

                return View(viewModel);
            }

            _dbContext.Videos.Add(video);
            _dbContext.SaveChanges();
            return RedirectToAction("Index", "Locations");
        }

        // GET: VideoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: VideoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VideoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: VideoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CulturalHeritageWebApp/Views/Locations/Create.cshtml
@model CulturalHeritageWebApp.ViewModels.VMHeritage

@{
    ViewData["Title"] = "Create";
}


<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/create.css">
</head>
<body>

    <div class="create">

            <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="create-group" style="display: none;">
                        <label asp-for="IDHeritage" class="control-label"></label>
                        <input asp-for="IDHeritage" class="form-control" type="hidden" />
                        <span asp-validation-for="IDHeritage" class="text-danger"></span>
                    </div>
            <div class="create-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
            <div class="create-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
            <div class="create-group">
                        @Html.LabelFor(model => model.AgeCategoryID, "Period", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.AgeCategoryID, Model.AgeCategoryList, "Select Age Category", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.AgeCategoryID, "", new { @class = "text-danger" })
                        </div>
                    </div>
            <div class="create-group">
                        <label asp-for="HeritageCategoryID" class="control-label">Heritage Category: Cultural Location</label>
                        <input asp-for="HeritageCategoryID" class="form-control" type="hidden" value="1" />
                        <span asp-validation-for="HeritageCategoryID" class="text-danger"></span>
                    </div>

            <div class="create-group">
                        <input type="submit" value="Create" class="hero-btn" />
                    </div>
            </form>


        <div>
            <a asp-action="Index" class="hero-btn">Back to List</a>
        </div>

    </div>

    @*Footer*@

    <section class="footer">
        <h4>About Us</h4>
        <p>
            Create. Protect. Share.
        </p>
        <div class="icons">
            <img src="~/Photos/face-logo.png" class="logo" />
            <img src="~/Photos/insta-logo.png" class="logo" />
            <img src="~/Photos/tik-tok-logo.png" class="logo" />
            <img src="~/Photos/x-logo.png" class="logo" />
        </div>
    </section>

        @section Scripts {
            @{
                await Html.RenderPartialAsync("_ValidationScriptsPartial");
            }
        }


</body>
</html>

CulturalHeritageWebApp/Views/Locations/Delete.cshtml
@model CulturalHeritageWebApp.ViewModels.VMHeritage

@{
    ViewData["Title"] = "Delete";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/delete.css">
</head>
<body>
        <div class="delete">

            <div class="formDelete">

                <h3>Are you sure you want to delete this?</h3>

                    <dl class="row">
                        <dt class="col-sm-2" style="display: none;">
                            @Html.DisplayNameFor(model => model.IDHeritage)
                        </dt>
                        <dd class="col-sm-10" style="display: none;">
                            @Html.DisplayFor(model => model.IDHeritage)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Title)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Title)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Description)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Description)
                        </dd>
                        <dt class="col-sm-2" style="display: none;">
                            @Html.DisplayNameFor(model => model.AgeCategoryID)
                        </dt>
                        <dd class="col-sm-10" style="display: none;">
                            @Html.DisplayFor(model => model.AgeCategory.Name)
                        </dd>
                        <dt class="col-sm-2" style="display: none;">
                            @Html.DisplayNameFor(model => model.HeritageCategoryID)
                        </dt>
                        <dd class="col-sm-10" style="display: none;">
                            @Html.DisplayFor(model => model.HeritageCategoryID)
                        </dd>
                    </dl>

                    <form asp-action="Delete">
                        <input type="submit" value="Delete" class="btn btn-danger" /> <br />
                        <a asp-action="Index" class="hero-btn">Back to List</a>
                    </form>
            </div>
        </div>

    @*Footer*@

    <section class="footer">
        <h4>About Us</h4>
        <p>
            Create. Protect. Share.
        </p>
        <div class="icons">
            <img src="~/Photos/face-logo.png" class="logo" />
            <img src="~/Photos/insta-logo.png" class="logo" />
            <img src="~/Photos/tik-tok-logo.png" class="logo" />
            <img src="~/Photos/x-logo.png" class="logo" />
        </div>
    </section>

</body>
</html>

CulturalHeritageWebApp/Views/Locations/Details.cshtml
@model CulturalHeritageWebApp.ViewModels.VMHeritage

@{
    ViewData["Title"] = "Details";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/details.css">
    <link rel="stylesheet" href="~/lib/jquery.flipster.min.css">
</head>
<body>
    <div class="gallery">
        <div class="carousel">
            <ul>
                @foreach (var photo in Model.Photographies)
                {
                    <li>
                        @if (!string.IsNullOrEmpty(photo.PicturePath))
                        {
                            <img src="@photo.PicturePath" alt="@photo.Description"/>
                        }
                    </li>
                }

            </ul>
        </div>
    </div>

    <section class="video">
        <div class="video-row">
            <div class="video-col">
                @foreach (var video in Model.Videos)
                {
                    <div class="video-item">
                        <!-- YouTube video using iframe -->
                        <iframe width="560" height="315" src="@video.VideoPath" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                    </div>
                }
            </div>
            <div class="video-col">
                <a asp-action="Index" class="hero-btn">Back to List</a>
            </div>
        </div>
    </section>



    @*Footer*@

    <section class="footer">
        <h4>About Us</h4>
        <p>
            Create. Protect. Share.
        </p>
        <div class="icons">
            <img src="~/Photos/face-logo.png" class="logo" />
            <img src="~/Photos/insta-logo.png" class="logo" />
            <img src="~/Photos/tik-tok-logo.png" class="logo" />
            <img src="~/Photos/x-logo.png" class="logo" />
        </div>
    </section>



<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="~/lib/jquery.flipster.min.js"></script>

<script>
        $('.carousel').flipster({
            style: 'carousel',
            spacing: -0.3,
        });
</script>
</body>
</html>

CulturalHeritageWebApp/Views/Locations/Edit.cshtml
@model CulturalHeritageWebApp.ViewModels.VMHeritage

@{
    ViewData["Title"] = "Edit";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/edit.css">
</head>
<body>
    
    <div class="edit">
        <form asp-action="Edit">
            <div class="edit-group" style="display: none;">
                <label asp-for="IDHeritage" class="control-label"></label>
                <input asp-for="IDHeritage" class="form-control" />
                <span asp-validation-for="IDHeritage" class="text-danger"></span>
            </div>
            <div class="edit-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" id="title"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="edit-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="edit-group">
                @Html.LabelFor(model => model.AgeCategoryID, "Period", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.AgeCategoryID, Model.AgeCategoryList, "Select Age Category", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AgeCategoryID, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="edit-group" style="display: none;">
                <label asp-for="HeritageCategoryID" class="control-label">Heritage Category: Location</label>
                <input asp-for="HeritageCategoryID" class="form-control" type="hidden" value="1" />
                <span asp-validation-for="HeritageCategoryID" class="text-danger"></span>
            </div>
            <div class="edit-group">
                <a asp-controller="Photography" asp-action="Create" asp-route-heritageID="@Model.IDHeritage" class="hero-btn">Add Photography</a>
                <a asp-controller="Video" asp-action="Create" asp-route-heritageID="@Model.IDHeritage" class="hero-btn">Add Video</a>
            </div>

            <div class="edit-group">
                <input type="submit" value="Save" class="hero-btn save" />
            </div>

        </form>
                

        <div>
            <a asp-action="Index" class="hero-btn">Back to List</a>
        </div>

    </div>



@*Footer*@

<section class="footer">
    <h4>About Us</h4>
    <p>
        Create. Protect. Share.
    </p>
    <div class="icons">
        <img src="~/Photos/face-logo.png" class="logo" />
        <img src="~/Photos/insta-logo.png" class="logo" />
        <img src="~/Photos/tik-tok-logo.png" class="logo" />
        <img src="~/Photos/x-logo.png" class="logo" />
    </div>
</section>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

</body>
</html>

CulturalHeritageWebApp/Views/Locations/Index.cshtml
@model IEnumerable<CulturalHeritageWebApp.ViewModels.VMHeritage>

@{
    ViewData["Title"] = "Index";
}


<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/locations.css">
</head>
<body>
    <section class="header">
        <nav>
            <img src="~/Photos/vase.png">
            <div class="nav-links" id="navLinks">
                <img src="~/Photos/closing.png" class="fa" style="width:15px; height: 15px" onclick="hideMenu()" />
                <ul>
                    <li><a asp-controller="Home" asp-action="Index">HOME <span>&vert;</span></a></li>
                    <li><a asp-controller="Locations" asp-action="Index">Cultural Locations <span>&vert;</span></a></li>
                    <li><a asp-controller="Intangible" asp-action="Index">Intangible Heritage <span>&vert;</span></a></li>
                    <li><a asp-controller="Tangible" asp-action="Index">Tangible Heritage <span>&vert;</span></a></li>
                    <li><a asp-controller="Home" asp-action="Education">Education <span>&vert;</span></a></li>
                    <li><a asp-controller="Home" asp-action="About">About Us</a></li>
                </ul>
            </div>
            <img src="~/Photos/menu.png" style="width:25px; height: 25px" class="fa" onclick="showMenu()" />
        </nav>
        <div class="text-box">
            <h1>CULTURAL LOCATIONS</h1>
        </div>
    </section>

    @*Create*@

    <section class="createLocations">
        <div class="row">
            <div class="create-col">
                <p>Cultural locations encompass a rich tapestry of historical, artistic, and heritage sites that bear significance due to their cultural value.
                    These places, ranging from museums, landmarks, and religious buildings to archaeological sites and cultural centers,
                    stand as custodians of a community's history, preserving and sharing its cultural identity, traditions, and stories with the world.
                </p>
                <h5>Give your contribution and enter a new object</h5>
                <a asp-action="Create" class="hero-btn">CREATE NEW</a>
               
            </div>
            <div class="create-col">
                <img src="~/Photos/parthenon.jpg">
            </div>
        </div>
    </section>


    @*Locations*@

    <section class="locations">
        <h1> Explore Cultural Locations </h1>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="locations-col">
                    @if (item.Photographies.Any() && !string.IsNullOrEmpty(item.Photographies.First().PicturePath))
                    {
                        <img src="@item.Photographies.First().PicturePath" class="card-img-top" alt="Heritage Image" style="height: 500px;">
                    }
                </div>
                <div class="locations-col">
                    <h5 class="card-title">@item.Title</h5>
                    <p class="card-text"> <strong>Period: </strong> @item.AgeCategory.Name</p>
                    <p class="card-text">@item.Description</p>
                    <div class="buttons">
                        <a href="@Url.Action("Details", new { id = item.IDHeritage })" class="details-btn">Gallery</a>
                        <div class="btnEditDelete">
                             <a href="@Url.Action("Edit", new { id = item.IDHeritage })" class="edit-btn">Edit</a>
                             <a href="@Url.Action("Delete", new { id = item.IDHeritage })" class="delete-btn">Delete</a>
                         </div>
                    </div>
                </div>
            }
        </div>
    </section>


    @*Footer*@

    <section class="footer">
        <h4>About Us</h4>
        <p>
            Create. Protect. Share.
        </p>
        <div class="icons">
            <img src="~/Photos/face-logo.png" class="logo" />
            <img src="~/Photos/insta-logo.png" class="logo" />
            <img src="~/Photos/tik-tok-logo.png" class="logo" />
            <img src="~/Photos/x-logo.png" class="logo" />
        </div>
    </section>

    @*JavaSript for Toggle Menu*@
    <script src="~/js/site.js"></script>

</body>
</html>